export const users = [
  {
    id: 1,
    socketId: 43214,
    username: 'johnDoe92',
    email: 'john.doe92@example.com',
    password: 'password123',
    first_name: 'John',
    last_name: 'Doe',
    picture: 'https://example.com/pictures/johndoe92.jpg',
  },
  {
    id: 2,
    socketId: 431542,
    username: 'janeSmith85',
    email: 'jane.smith85@example.com',
    password: 'securePass!45',
    first_name: 'Jane',
    last_name: 'Smith',
    picture: 'https://example.com/pictures/janesmith85.jpg',
  },
  {
    id: 3,
    socketId: 4545,
    username: 'mikeBrown78',
    email: 'mike.brown78@example.com',
    password: 'mikeB@78password',
    first_name: 'Mike',
    last_name: 'Brown',
    picture: 'https://example.com/pictures/mikebrown78.jpg',
  },
  {
    id: 4,
    socketId: 53423425,
    username: 'emilyClark88',
    email: 'emily.clark88@example.com',
    password: 'emily!Clark88',
    first_name: 'Emily',
    last_name: 'Clark',
    picture: 'https://example.com/pictures/emilyclark88.jpg',
  },
  {
    id: 5,
    socketId: 54523,
    username: 'danielLee90',
    email: 'daniel.lee90@example.com',
    password: 'danielLee90pass',
    first_name: 'Daniel',
    last_name: 'Lee',
    picture: 'https://example.com/pictures/daniellee90.jpg',
  },
  {
    id: 6,
    socketId: 563234,
    username: 'sarahMiller83',
    email: 'sarah.miller83@example.com',
    password: 'SarahMiller!83',
    first_name: 'Sarah',
    last_name: 'Miller',
    picture: 'https://example.com/pictures/sarahmiller83.jpg',
  },
  {
    id: 7,
    socketId: 54545,
    username: 'chrisJohnson81',
    email: 'chris.johnson81@example.com',
    password: 'johnsonChris81*',
    first_name: 'Chris',
    last_name: 'Johnson',
    picture: 'https://example.com/pictures/chrisjohnson81.jpg',
  },
  {
    id: 8,
    socketId: 47428,
    username: 'oliviaTaylor94',
    email: 'olivia.taylor94@example.com',
    password: 'OliviaT@94password',
    first_name: 'Olivia',
    last_name: 'Taylor',
    picture: 'https://example.com/pictures/oliviataylor94.jpg',
  },
  {
    id: 9,
    socketId: 5489759,
    username: 'jamesAnderson79',
    email: 'james.anderson79@example.com',
    password: 'James79Anderson!',
    first_name: 'James',
    last_name: 'Anderson',
    picture: 'https://example.com/pictures/jamesanderson79.jpg',
  },
  {
    id: 10,
    socketId: 43874,
    username: 'lauraWilson77',
    email: 'laura.wilson77@example.com',
    password: 'lauraWilson77#',
    first_name: 'Laura',
    last_name: 'Wilson',
    picture: 'https://example.com/pictures/laurawilson77.jpg',
  },
];

export const contacts = [
  { ...users[1], last_message: 'fhodahfod fasdfa' },
  { ...users[2], last_message: 'fhodahfod fasdfa' },
  { ...users[4], last_message: 'fhodahfod fasdfa' },
  { ...users[6], last_message: 'fhodahfod fasdfa' },
  { ...users[7], last_message: 'fhodahfod fasdfa' },
  { ...users[8], last_message: 'fhodahfod fasdfa' },
];
